# Generated by Django 6.0.2 on 2026-02-22 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(max_length=100, unique=True)),
                ('user_address', models.CharField(max_length=100)),
                ('amount_lamports', models.BigIntegerField()),
                ('transaction_type', models.CharField(choices=[('RECEIVED', 'Received Payment'), ('RETURNED', 'Returned Payment')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
